/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package laboratoriouno.cotizaciondivisas;

import javax.swing.ImageIcon;
import laboratoriouno.cotizaciondivisas.conector.TablaCotizaciones;
import laboratoriouno.cotizaciondivisas.modelo.AdministracionDivisasUsuarios;
import laboratoriouno.cotizaciondivisas.modelo.Moneda;
import laboratoriouno.cotizaciondivisas.modelo.MonedaCotizacion;

/**
 *
 * @author Jere
 */
public class FrameTablaCotizacion extends javax.swing.JFrame {

    private AdministracionDivisasUsuarios modeloApp = null;
    private FrameCRUDUsuarios fcrudusuarios = null;
    private FrameInicioSesion finiciosesion = null;
    private TablaCotizaciones conectorTablaCotizaciones;

    /**
     * Creates new form FrameTablaCotizacion
     */ //CotizacionesDeDivisas cd
    public FrameTablaCotizacion() {
        initComponents();
        this.conectorTablaCotizaciones = (TablaCotizaciones) this.tablaCotizaciones.getModel();
        this.conectorTablaCotizaciones.addTableModelListener(this.tablaCotizaciones);
    }

    public AdministracionDivisasUsuarios obtenerAplicaccion() {
        return this.modeloApp;
    }

    public void asignarAplicacion(AdministracionDivisasUsuarios a) {
        this.modeloApp = a;
    }

    public void asignarFrameCRUDUsuarios(FrameCRUDUsuarios fc) {
        this.fcrudusuarios = fc;

    }
    
    public void asignarFrameIniciSesion(FrameInicioSesion fis) {
        this.finiciosesion = fis;
        this.textUsuarioActivo.setText("Sesion iniciada como: "+this.finiciosesion.getNombreUsuario());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        comboBoxDivisas = new javax.swing.JComboBox();
        botonAgregar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablaCotizaciones = new javax.swing.JTable();
        botonActualizar = new javax.swing.JButton();
        botonEliminarUltimaFila = new javax.swing.JButton();
        botonAdminUsuarios = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        textUsuarioActivo = new javax.swing.JTextPane();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Cotizacion de monedas");
        setIconImage(new ImageIcon(this.getClass().getResource("ico.png")).getImage());
        setResizable(false);

        comboBoxDivisas.setModel(new laboratoriouno.cotizaciondivisas.conector.ComboBoxDivisas());

        botonAgregar.setText("Agregar");
        botonAgregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonAgregarActionPerformed(evt);
            }
        });

        tablaCotizaciones.setModel(new laboratoriouno.cotizaciondivisas.conector.TablaCotizaciones());
        jScrollPane1.setViewportView(tablaCotizaciones);

        botonActualizar.setText("Actualizar");
        botonActualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonActualizarActionPerformed(evt);
            }
        });

        botonEliminarUltimaFila.setText("Eliminar última");
        botonEliminarUltimaFila.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonEliminarUltimaFilaActionPerformed(evt);
            }
        });

        botonAdminUsuarios.setText("Administrar usuarios");
        botonAdminUsuarios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonAdminUsuariosActionPerformed(evt);
            }
        });

        textUsuarioActivo.setEditable(false);
        textUsuarioActivo.setBackground(getBackground());
        textUsuarioActivo.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        jScrollPane2.setViewportView(textUsuarioActivo);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(botonActualizar)
                                .addGap(190, 190, 190)
                                .addComponent(botonAdminUsuarios, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(comboBoxDivisas, javax.swing.GroupLayout.PREFERRED_SIZE, 209, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(botonAgregar)
                                .addGap(18, 18, 18)
                                .addComponent(botonEliminarUltimaFila, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.LEADING))
                .addGap(15, 15, 15))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(comboBoxDivisas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(botonAgregar)
                    .addComponent(botonEliminarUltimaFila))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 275, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(botonActualizar)
                    .addComponent(botonAdminUsuarios))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void botonAgregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonAgregarActionPerformed
        Moneda monedaSeleccionada = (Moneda) comboBoxDivisas.getSelectedItem();
        MonedaCotizacion monedaParaInsertar = this.modeloApp.obtenerUnaCotizacion(monedaSeleccionada);
        this.conectorTablaCotizaciones.agregarCotizacion(monedaParaInsertar);

    }//GEN-LAST:event_botonAgregarActionPerformed

    private void botonActualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonActualizarActionPerformed
    }//GEN-LAST:event_botonActualizarActionPerformed

    private void botonEliminarUltimaFilaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonEliminarUltimaFilaActionPerformed
        this.conectorTablaCotizaciones.eliminarUltimaFila();
    }//GEN-LAST:event_botonEliminarUltimaFilaActionPerformed

    private void botonAdminUsuariosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonAdminUsuariosActionPerformed
        if (this.fcrudusuarios == null) {
            fcrudusuarios = new FrameCRUDUsuarios();
            fcrudusuarios.asignarAplicacion(this.modeloApp);
            this.fcrudusuarios.asignarFramePrincipal(this);
        }
        this.setVisible(false);
        fcrudusuarios.setVisible(true);
    }//GEN-LAST:event_botonAdminUsuariosActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;


                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrameTablaCotizacion.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrameTablaCotizacion.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrameTablaCotizacion.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrameTablaCotizacion.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form*/

        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrameTablaCotizacion().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botonActualizar;
    private javax.swing.JButton botonAdminUsuarios;
    private javax.swing.JButton botonAgregar;
    private javax.swing.JButton botonEliminarUltimaFila;
    private javax.swing.JComboBox comboBoxDivisas;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable tablaCotizaciones;
    private javax.swing.JTextPane textUsuarioActivo;
    // End of variables declaration//GEN-END:variables
}
