/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package laboratoriouno.cotizaciondivisas;

import java.awt.Component;
import java.awt.event.KeyEvent;
import java.util.ArrayList;
import java.util.List;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import laboratoriouno.cotizaciondivisas.conector.ComboBoxDivisas;
import laboratoriouno.cotizaciondivisas.conector.TablaCotizaciones;
import laboratoriouno.cotizaciondivisas.conector.TablaUsuarios;
import laboratoriouno.cotizaciondivisas.modelo.AdministracionDivisasUsuarios;
import laboratoriouno.cotizaciondivisas.modelo.Moneda;
import laboratoriouno.cotizaciondivisas.modelo.MonedaCotizacion;
import laboratoriouno.cotizaciondivisas.modelo.Usuario;

/**
 *
 * @author Jere
 */
public class FrameCotizacionDivisas extends javax.swing.JFrame {

    private AdministracionDivisasUsuarios modeloApp;
    private TablaCotizaciones conectorTablaCotizaciones;
    private TablaUsuarios conectorTablaUsuarios;
    private ComboBoxDivisas conectorComboBoxDivisas;
    private String nombreUsuarioSeleccionado_tabAdmin = new String();

    /**
     * Creates new form FrameCotizacionDivisas
     */
    public FrameCotizacionDivisas(AdministracionDivisasUsuarios app) {
        this.modeloApp = app;

        initComponents();
        /*this.conectorComboBoxDivisas = (ComboBoxDivisas) this.comboBoxDivisas_tabCotiza.getModel();
         this.conectorComboBoxDivisas.addListDataListener(comboBoxDivisas_tabCotiza);*/

        this.conectorTablaCotizaciones = (TablaCotizaciones) this.tablaCotizaciones_tabCotiza.getModel();
        this.conectorTablaCotizaciones.addTableModelListener(this.tablaCotizaciones_tabCotiza);

        this.conectorTablaUsuarios = (TablaUsuarios) this.tablaUsuarios_tabAdmin.getModel();
        this.conectorTablaUsuarios.addTableModelListener(tablaUsuarios_tabAdmin);
        this.conectorTablaUsuarios.cargarUsuarios(modeloApp);




    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelCotizacionDivisas = new javax.swing.JTabbedPane();
        tabSesionUsuario = new javax.swing.JPanel();
        panelIniciarSesion = new javax.swing.JPanel();
        campoNombreUsuario_tabSesion = new javax.swing.JTextField();
        campoClaveAcceso_tabSesion = new javax.swing.JPasswordField();
        botonAcceder_tabSesion = new javax.swing.JButton();
        etiquetaUsuarioActivo_tabSesion = new java.awt.Label();
        botonCerrarSesion_tabSesion = new javax.swing.JButton();
        tabCotizacionDivisas = new javax.swing.JPanel();
        etiquetaUsuarioActivo_tabCotiza = new java.awt.Label();
        comboBoxDivisas_tabCotiza = new javax.swing.JComboBox();
        botonAgregar_tabCotiza = new javax.swing.JButton();
        botonEliminarUltima_tabCotiza = new javax.swing.JButton();
        scrollCotizaciones_tabCotiza = new javax.swing.JScrollPane();
        tablaCotizaciones_tabCotiza = new javax.swing.JTable();
        botonActualizar_tabCotiza = new javax.swing.JButton();
        tabAdminUsuarios = new javax.swing.JPanel();
        scrollUsuarios_tabAdmin = new javax.swing.JScrollPane();
        tablaUsuarios_tabAdmin = new javax.swing.JTable();
        panelAdminUsuarios = new javax.swing.JPanel();
        campoClaveAcceso_tabAdmin = new javax.swing.JTextField();
        campoNombreUsuario_tabAdmin = new javax.swing.JTextField();
        botonAgregar_tabAdmin = new javax.swing.JButton();
        botonEliminar_tabAdmin = new javax.swing.JButton();
        botonActualizar_tabAdmin = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("my.DolarBlue()");
        setIconImage(new ImageIcon(this.getClass().getResource("ico.png")).getImage());
        setResizable(false);

        panelIniciarSesion.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));

        campoNombreUsuario_tabSesion.setText("Nombre de usuario");

        campoClaveAcceso_tabSesion.setText("Clave de acceso");
        campoClaveAcceso_tabSesion.setToolTipText("Clave de acceso");

        botonAcceder_tabSesion.setText("Acceder");
        botonAcceder_tabSesion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonAcceder_tabSesionActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelIniciarSesionLayout = new javax.swing.GroupLayout(panelIniciarSesion);
        panelIniciarSesion.setLayout(panelIniciarSesionLayout);
        panelIniciarSesionLayout.setHorizontalGroup(
            panelIniciarSesionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelIniciarSesionLayout.createSequentialGroup()
                .addContainerGap(28, Short.MAX_VALUE)
                .addGroup(panelIniciarSesionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(campoNombreUsuario_tabSesion, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(campoClaveAcceso_tabSesion, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(botonAcceder_tabSesion))
                .addGap(25, 25, 25))
        );
        panelIniciarSesionLayout.setVerticalGroup(
            panelIniciarSesionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelIniciarSesionLayout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(campoNombreUsuario_tabSesion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(campoClaveAcceso_tabSesion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 30, Short.MAX_VALUE)
                .addComponent(botonAcceder_tabSesion)
                .addContainerGap())
        );

        botonCerrarSesion_tabSesion.setText("Cerrar sesión");
        botonCerrarSesion_tabSesion.setEnabled(false);
        botonCerrarSesion_tabSesion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonCerrarSesion_tabSesionActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout tabSesionUsuarioLayout = new javax.swing.GroupLayout(tabSesionUsuario);
        tabSesionUsuario.setLayout(tabSesionUsuarioLayout);
        tabSesionUsuarioLayout.setHorizontalGroup(
            tabSesionUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tabSesionUsuarioLayout.createSequentialGroup()
                .addGroup(tabSesionUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(tabSesionUsuarioLayout.createSequentialGroup()
                        .addGap(139, 139, 139)
                        .addGroup(tabSesionUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(panelIniciarSesion, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(etiquetaUsuarioActivo_tabSesion, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(tabSesionUsuarioLayout.createSequentialGroup()
                        .addGap(185, 185, 185)
                        .addComponent(botonCerrarSesion_tabSesion)))
                .addContainerGap(144, Short.MAX_VALUE))
        );
        tabSesionUsuarioLayout.setVerticalGroup(
            tabSesionUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tabSesionUsuarioLayout.createSequentialGroup()
                .addGap(45, 45, 45)
                .addComponent(etiquetaUsuarioActivo_tabSesion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panelIniciarSesion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(botonCerrarSesion_tabSesion)
                .addContainerGap(36, Short.MAX_VALUE))
        );

        panelCotizacionDivisas.addTab("Sesión de usuario", tabSesionUsuario);

        etiquetaUsuarioActivo_tabCotiza.setText("No se ha iniciado sesion");

        comboBoxDivisas_tabCotiza.setMaximumRowCount(10);
        comboBoxDivisas_tabCotiza.setModel(new ComboBoxDivisas(this.modeloApp));

        botonAgregar_tabCotiza.setText("Agregar moneda");
        botonAgregar_tabCotiza.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonAgregar_tabCotizaActionPerformed(evt);
            }
        });

        botonEliminarUltima_tabCotiza.setText("Eliminar última moneda");
        botonEliminarUltima_tabCotiza.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonEliminarUltima_tabCotizaActionPerformed(evt);
            }
        });

        tablaCotizaciones_tabCotiza.setModel(new TablaCotizaciones());
        scrollCotizaciones_tabCotiza.setViewportView(tablaCotizaciones_tabCotiza);

        botonActualizar_tabCotiza.setText("Actualizar cotizaciones");
        botonActualizar_tabCotiza.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonActualizar_tabCotizaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout tabCotizacionDivisasLayout = new javax.swing.GroupLayout(tabCotizacionDivisas);
        tabCotizacionDivisas.setLayout(tabCotizacionDivisasLayout);
        tabCotizacionDivisasLayout.setHorizontalGroup(
            tabCotizacionDivisasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tabCotizacionDivisasLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(tabCotizacionDivisasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(etiquetaUsuarioActivo_tabCotiza, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(tabCotizacionDivisasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(tabCotizacionDivisasLayout.createSequentialGroup()
                            .addComponent(comboBoxDivisas_tabCotiza, javax.swing.GroupLayout.PREFERRED_SIZE, 254, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(botonAgregar_tabCotiza, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(tabCotizacionDivisasLayout.createSequentialGroup()
                            .addComponent(botonActualizar_tabCotiza)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(botonEliminarUltima_tabCotiza))
                        .addComponent(scrollCotizaciones_tabCotiza, javax.swing.GroupLayout.PREFERRED_SIZE, 447, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        tabCotizacionDivisasLayout.setVerticalGroup(
            tabCotizacionDivisasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tabCotizacionDivisasLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(etiquetaUsuarioActivo_tabCotiza, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(tabCotizacionDivisasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(comboBoxDivisas_tabCotiza, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(botonAgregar_tabCotiza))
                .addGap(18, 18, 18)
                .addComponent(scrollCotizaciones_tabCotiza, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(tabCotizacionDivisasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(botonEliminarUltima_tabCotiza)
                    .addComponent(botonActualizar_tabCotiza))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        panelCotizacionDivisas.addTab("Cotización de divisas", tabCotizacionDivisas);

        tablaUsuarios_tabAdmin.setModel(new TablaUsuarios());
        tablaUsuarios_tabAdmin.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tablaUsuarios_tabAdminMouseClicked(evt);
            }
        });
        tablaUsuarios_tabAdmin.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                tablaUsuarios_tabAdminKeyPressed(evt);
            }
        });
        scrollUsuarios_tabAdmin.setViewportView(tablaUsuarios_tabAdmin);

        panelAdminUsuarios.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        campoClaveAcceso_tabAdmin.setText("Clave de acceso");

        campoNombreUsuario_tabAdmin.setText("Nombre de usuario");

        botonAgregar_tabAdmin.setText("Agregar");
        botonAgregar_tabAdmin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonAgregar_tabAdminActionPerformed(evt);
            }
        });

        botonEliminar_tabAdmin.setText("Eliminar");
        botonEliminar_tabAdmin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonEliminar_tabAdminActionPerformed(evt);
            }
        });

        botonActualizar_tabAdmin.setText("Actualizar");
        botonActualizar_tabAdmin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonActualizar_tabAdminActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelAdminUsuariosLayout = new javax.swing.GroupLayout(panelAdminUsuarios);
        panelAdminUsuarios.setLayout(panelAdminUsuariosLayout);
        panelAdminUsuariosLayout.setHorizontalGroup(
            panelAdminUsuariosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelAdminUsuariosLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelAdminUsuariosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(campoClaveAcceso_tabAdmin)
                    .addComponent(campoNombreUsuario_tabAdmin)
                    .addGroup(panelAdminUsuariosLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(botonAgregar_tabAdmin, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(botonEliminar_tabAdmin, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(botonActualizar_tabAdmin)))
                .addContainerGap())
        );
        panelAdminUsuariosLayout.setVerticalGroup(
            panelAdminUsuariosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelAdminUsuariosLayout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addComponent(campoNombreUsuario_tabAdmin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(4, 4, 4)
                .addComponent(campoClaveAcceso_tabAdmin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panelAdminUsuariosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(botonEliminar_tabAdmin)
                    .addComponent(botonActualizar_tabAdmin)
                    .addComponent(botonAgregar_tabAdmin))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout tabAdminUsuariosLayout = new javax.swing.GroupLayout(tabAdminUsuarios);
        tabAdminUsuarios.setLayout(tabAdminUsuariosLayout);
        tabAdminUsuariosLayout.setHorizontalGroup(
            tabAdminUsuariosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, tabAdminUsuariosLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(tabAdminUsuariosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(scrollUsuarios_tabAdmin, javax.swing.GroupLayout.DEFAULT_SIZE, 447, Short.MAX_VALUE)
                    .addComponent(panelAdminUsuarios, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        tabAdminUsuariosLayout.setVerticalGroup(
            tabAdminUsuariosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tabAdminUsuariosLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(scrollUsuarios_tabAdmin, javax.swing.GroupLayout.DEFAULT_SIZE, 171, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(panelAdminUsuarios, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        panelCotizacionDivisas.addTab("Administración de usuarios", tabAdminUsuarios);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelCotizacionDivisas)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(panelCotizacionDivisas, javax.swing.GroupLayout.PREFERRED_SIZE, 323, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void botonAgregar_tabCotizaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonAgregar_tabCotizaActionPerformed
        Moneda monedaSeleccionada = (Moneda) this.comboBoxDivisas_tabCotiza.getSelectedItem();
        this.modeloApp.agregarMonedaDeUsuario(monedaSeleccionada);

        MonedaCotizacion monedaParaInsertar = this.modeloApp.obtenerUnaCotizacion(monedaSeleccionada);
        this.conectorTablaCotizaciones.agregarCotizacion(monedaParaInsertar);
        this.conectorTablaUsuarios.cargarUsuarios(modeloApp);
    }//GEN-LAST:event_botonAgregar_tabCotizaActionPerformed

    private void botonEliminarUltima_tabCotizaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonEliminarUltima_tabCotizaActionPerformed
        if (this.modeloApp.sesionIniciada() && this.conectorTablaCotizaciones.getRowCount() > 0) {
            int ultimaFila = this.conectorTablaCotizaciones.getRowCount() - 1;
            String siglas = (String) this.conectorTablaCotizaciones.getValueAt(ultimaFila, 0);

            this.modeloApp.eliminarMonedaDeUsuario(siglas);
            this.conectorTablaUsuarios.cargarUsuarios(modeloApp);
        }
        this.conectorTablaCotizaciones.eliminarUltimaFila();
    }//GEN-LAST:event_botonEliminarUltima_tabCotizaActionPerformed

    private void botonAcceder_tabSesionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonAcceder_tabSesionActionPerformed
        String nombre = this.campoNombreUsuario_tabSesion.getText();
        char[] clave = this.campoClaveAcceso_tabSesion.getPassword();
        Usuario u = this.modeloApp.obtenerUsuario(nombre);

        if (u.tieneNombre()) {
            if (this.modeloApp.iniciarSesion(u, clave)) {
                this.iniciarSesion(u);
            }
        }
    }//GEN-LAST:event_botonAcceder_tabSesionActionPerformed

    private void iniciarSesion(Usuario u) {
        for (Component c : this.panelIniciarSesion.getComponents()) {
            c.setEnabled(false);
        }
        this.etiquetaUsuarioActivo_tabSesion.setText("Usuario activo: " + u.getNombre());
        this.etiquetaUsuarioActivo_tabCotiza.setText("Usuario activo: " + u.getNombre());
        this.botonCerrarSesion_tabSesion.setEnabled(true);
        this.conectorTablaCotizaciones.limpiarTabla();
        this.conectorTablaCotizaciones.cargarMonedasUsuario(u, modeloApp);

    }

    private void cerrarSesion() {
        for (Component c : this.panelIniciarSesion.getComponents()) {
            c.setEnabled(true);
        }
        this.etiquetaUsuarioActivo_tabSesion.setText("");
        this.etiquetaUsuarioActivo_tabCotiza.setText("No se ha iniciado sesion");
        this.campoNombreUsuario_tabSesion.setText("Nombre de usuario");
        this.campoClaveAcceso_tabSesion.setText("Clave de acceso");
        this.botonCerrarSesion_tabSesion.setEnabled(false);
        this.conectorTablaCotizaciones.limpiarTabla();
    }

    private void restaurarCamposUsuario_tabAdmin() {
        this.campoNombreUsuario_tabAdmin.setText("Nombre de usuario");
        this.campoClaveAcceso_tabAdmin.setText("Clave de acceso");
        this.botonAgregar_tabAdmin.setEnabled(true);
        this.tablaUsuarios_tabAdmin.clearSelection();
    }
    private void botonCerrarSesion_tabSesionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonCerrarSesion_tabSesionActionPerformed
        this.modeloApp.cerrarSesion();
        this.cerrarSesion();
    }//GEN-LAST:event_botonCerrarSesion_tabSesionActionPerformed

    private void botonAgregar_tabAdminActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonAgregar_tabAdminActionPerformed
        if (this.tablaUsuarios_tabAdmin.getSelectedRow() == -1) {
            String claveConfirmada = JOptionPane.showInputDialog(this, "Confirmar clave:", "Confirmar clave", JOptionPane.INFORMATION_MESSAGE);
            String nombre = this.campoNombreUsuario_tabAdmin.getText();
            String clave = this.campoClaveAcceso_tabAdmin.getText();
            if (claveConfirmada != null && !claveConfirmada.isEmpty()) {
                if (claveConfirmada.equals(clave)) {
                    Usuario u = new Usuario(nombre);
                    u.setClaveAcceso(clave);
                    this.modeloApp.agregarUsuario(u);
                    this.conectorTablaUsuarios.cargarUsuarios(modeloApp);
                    restaurarCamposUsuario_tabAdmin();
                }
            }
        }
    }//GEN-LAST:event_botonAgregar_tabAdminActionPerformed

    private void botonEliminar_tabAdminActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonEliminar_tabAdminActionPerformed
        if (this.tablaUsuarios_tabAdmin.getSelectedRow() > -1) {
            String nombre = (String) this.conectorTablaUsuarios.getValueAt(this.tablaUsuarios_tabAdmin.getSelectedRow(), 0);
            int respuesta = JOptionPane.showConfirmDialog(this.botonEliminar_tabAdmin, "¿Realmente desea eliminar \n al usuario " + nombre + "?", "Confirme eliminación", JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE);
            if (respuesta == JOptionPane.YES_OPTION) {
                Usuario u = this.modeloApp.obtenerUsuario(nombre);
                this.modeloApp.eliminarUsuario(u);
                this.conectorTablaUsuarios.cargarUsuarios(modeloApp);
            }
        }
        restaurarCamposUsuario_tabAdmin();
    }//GEN-LAST:event_botonEliminar_tabAdminActionPerformed

    private void botonActualizar_tabAdminActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonActualizar_tabAdminActionPerformed
        if (this.tablaUsuarios_tabAdmin.getSelectedRow() > -1) {
            String nombreOriginal = this.nombreUsuarioSeleccionado_tabAdmin;
            String nombreModificado = this.campoNombreUsuario_tabAdmin.getText();
            String nuevaClave = this.campoClaveAcceso_tabAdmin.getText();

            int respuesta = JOptionPane.showConfirmDialog(this.botonActualizar_tabAdmin, "¿Realmente desea actualizar \n datos del usuario " + nombreOriginal + "?", "Confirme actualización", JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE);
            if (respuesta == JOptionPane.YES_OPTION) {
                Usuario u = this.modeloApp.obtenerUsuario(nombreOriginal);
                if (!nombreOriginal.equals(nombreModificado)) {
                    this.modeloApp.modificarNombreUsuario(u, nombreModificado);
                }
                if (!nuevaClave.equals("*****")) {
                    this.modeloApp.modificarClaveUsuario(u, nuevaClave);
                }
                this.conectorTablaUsuarios.cargarUsuarios(modeloApp);
            }
        }
        restaurarCamposUsuario_tabAdmin();
    }//GEN-LAST:event_botonActualizar_tabAdminActionPerformed

    private void tablaUsuarios_tabAdminMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tablaUsuarios_tabAdminMouseClicked
        if (this.tablaUsuarios_tabAdmin.getSelectedRow() > -1) {
            String nombre = (String) this.conectorTablaUsuarios.getValueAt(this.tablaUsuarios_tabAdmin.getSelectedRow(), 0);
            this.nombreUsuarioSeleccionado_tabAdmin = nombre;
            this.campoNombreUsuario_tabAdmin.setText(nombre);
            this.campoClaveAcceso_tabAdmin.setText("*****");
            this.botonAgregar_tabAdmin.setEnabled(false);
        }
    }//GEN-LAST:event_tablaUsuarios_tabAdminMouseClicked

    private void tablaUsuarios_tabAdminKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tablaUsuarios_tabAdminKeyPressed
        String tecla = KeyEvent.getKeyText(evt.getKeyCode());
        if (tecla.equals("Escape")) {
            restaurarCamposUsuario_tabAdmin();
        }
    }//GEN-LAST:event_tablaUsuarios_tabAdminKeyPressed

    private void botonActualizar_tabCotizaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonActualizar_tabCotizaActionPerformed
        if (this.conectorTablaCotizaciones.getRowCount() > 0) {
            this.modeloApp.actualizarCotizaciones();
            List<String> siglas = new ArrayList();
            for (int i = 0; i <= this.conectorTablaCotizaciones.getRowCount() - 1; i++) {
                siglas.add(this.conectorTablaCotizaciones.getValueAt(i, 0).toString());
            }
            this.conectorTablaCotizaciones.limpiarTabla();
            for (String s : siglas) {
                MonedaCotizacion mc = this.modeloApp.obtenerUnaCotizacion(s);
                this.conectorTablaCotizaciones.agregarCotizacion(mc);
            }
            JOptionPane.showMessageDialog(this, "Cotizaciones actualizadas", "Actualizado", JOptionPane.INFORMATION_MESSAGE);
        }
    }//GEN-LAST:event_botonActualizar_tabCotizaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("WindowsLookAndFeel".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrameCotizacionDivisas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrameCotizacionDivisas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrameCotizacionDivisas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrameCotizacionDivisas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                //   new FrameCotizacionDivisas().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botonAcceder_tabSesion;
    private javax.swing.JButton botonActualizar_tabAdmin;
    private javax.swing.JButton botonActualizar_tabCotiza;
    private javax.swing.JButton botonAgregar_tabAdmin;
    private javax.swing.JButton botonAgregar_tabCotiza;
    private javax.swing.JButton botonCerrarSesion_tabSesion;
    private javax.swing.JButton botonEliminarUltima_tabCotiza;
    private javax.swing.JButton botonEliminar_tabAdmin;
    private javax.swing.JTextField campoClaveAcceso_tabAdmin;
    private javax.swing.JPasswordField campoClaveAcceso_tabSesion;
    private javax.swing.JTextField campoNombreUsuario_tabAdmin;
    private javax.swing.JTextField campoNombreUsuario_tabSesion;
    private javax.swing.JComboBox comboBoxDivisas_tabCotiza;
    private java.awt.Label etiquetaUsuarioActivo_tabCotiza;
    private java.awt.Label etiquetaUsuarioActivo_tabSesion;
    private javax.swing.JPanel panelAdminUsuarios;
    private javax.swing.JTabbedPane panelCotizacionDivisas;
    private javax.swing.JPanel panelIniciarSesion;
    private javax.swing.JScrollPane scrollCotizaciones_tabCotiza;
    private javax.swing.JScrollPane scrollUsuarios_tabAdmin;
    private javax.swing.JPanel tabAdminUsuarios;
    private javax.swing.JPanel tabCotizacionDivisas;
    private javax.swing.JPanel tabSesionUsuario;
    private javax.swing.JTable tablaCotizaciones_tabCotiza;
    private javax.swing.JTable tablaUsuarios_tabAdmin;
    // End of variables declaration//GEN-END:variables
}
