/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package laboratoriouno.cotizaciondivisas;

import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Jere
 */
public class FramePrincipal extends javax.swing.JFrame {

    /**
     * Creates new form FramePrincipal
     */
    public FramePrincipal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        comboBoxDivisas = new javax.swing.JComboBox();
        botonAgregar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablaCotizacion = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        comboBoxDivisas.setModel(new ModeloComboBoxDivisas());

        botonAgregar.setText("Agregar");
        botonAgregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonAgregarActionPerformed(evt);
            }
        });

        tablaCotizacion.setModel(new ModeloTablaCotizacion());
        jScrollPane1.setViewportView(tablaCotizacion);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(15, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 425, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(comboBoxDivisas, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(104, 104, 104)
                        .addComponent(botonAgregar)))
                .addGap(18, 18, 18))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(comboBoxDivisas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(botonAgregar))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 275, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(57, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void botonAgregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonAgregarActionPerformed
        DatosMoneda dm = (DatosMoneda) comboBoxDivisas.getSelectedItem();
        
        CreadorFila cf = new CreadorFila(dm.getSiglas());
        Moneda nuevamoneda = cf.crear();
        System.out.println("fila " + tablaCotizacion.getRowCount());
        ModeloTablaCotizacion m = (ModeloTablaCotizacion) tablaCotizacion.getModel();
        m.addRow();
        this.tablaCotizacion.setModel(m);
        System.out.println("fila " + tablaCotizacion.getRowCount());
        /*System.out.println("inserta "+nuevamoneda);
         this.tablaCotizacion.getModel().
         System.out.println("clase tabla "+tablaCotizacion.getClass().toString());
         DefaultTableModel temp = (DefaultTableModel) tablaCotizacion.getModel();
         // System.out.println("clase modelo tabla "+temp.getClass().toString());
         Object nuevo[]= {temp.getRowCount()+1,"",""};
         temp.addRow(nuevo);*/
        //int fila = tablaCotizacion.getRowCount()+1;
        //int columna = tablaCotizacion.getColumnCount();
        /*
         * DefaultTableModel temp = (DefaultTableModel) jTableProcesos.getModel();
         Object nuevo[]= {temp.getRowCount()+1,"",""};
         temp.addRow(nuevo);
         */
        /*
         tablaCotizacion.setValueAt(nuevamoneda , fila, 0);
         tablaCotizacion.setValueAt(nuevamoneda , fila, 1);
         */
        /*
         System.out.println(dm);
         System.out.println("fila " + tablaCotizacion.getRowCount());
         System.out.println("columna " + tablaCotizacion.getColumnCount());
         int r=tablaCotizacion.getModel().getRowCount();
         int c=tablaCotizacion.getModel().getColumnCount();
         this.tablaCotizacion.getModel().setValueAt(nuevamoneda, r, 0);
         this.tablaCotizacion.getModel().setValueAt(nuevamoneda, r, 1);*/
        
        
    }//GEN-LAST:event_botonAgregarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FramePrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FramePrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FramePrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FramePrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FramePrincipal().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botonAgregar;
    private javax.swing.JComboBox comboBoxDivisas;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tablaCotizacion;
    // End of variables declaration//GEN-END:variables
}
